#![allow(dead_code, unused_imports)]

mod common;

#[tokio::test]
#[ignore]
async fn test_config_loads_from_file() {
    todo!()
}

#[tokio::test]
#[ignore]
async fn test_env_vars_override_file() {
    todo!()
}

#[tokio::test]
#[ignore]
async fn test_missing_required_fields_error() {
    todo!()
}

#[tokio::test]
#[ignore]
async fn test_jwt_secret_autogenerated_when_blank() {
    todo!()
}

#[tokio::test]
#[ignore]
async fn test_world_readable_config_logs_warning() {
    todo!()
}

#[tokio::test]
#[ignore]
async fn test_llm_disabled_by_default() {
    todo!()
}

#[tokio::test]
#[ignore]
async fn test_debug_output_redacts_jwt_secret() {
    todo!()
}

