#![allow(dead_code, unused_imports)]

mod common;

use std::sync::OnceLock;

fn env_lock() -> &'static tokio::sync::Mutex<()> {
    static LOCK: OnceLock<tokio::sync::Mutex<()>> = OnceLock::new();
    LOCK.get_or_init(|| tokio::sync::Mutex::new(()))
}

#[tokio::test]
async fn test_config_loads_from_file() {
    let _guard = env_lock().lock().await;
    let dir = tempfile::tempdir().unwrap();
    let path = dir.path().join("config.toml");
    std::fs::write(
        &path,
        r#"
[app]
base_url = "https://example.com"
storage_path = "/var/lib/calibre"

[database]
url = "sqlite://books.db"

[auth]
jwt_secret = "MDEyMzQ1Njc4OWFiY2RlZjAxMjM0NTY3ODlhYmNkZWY"
"#,
    )
    .unwrap();

    std::env::set_var("CONFIG_PATH", &path);
    let config = backend::config::load_config().await.unwrap();
    std::env::remove_var("CONFIG_PATH");

    assert_eq!(config.app.base_url, "https://example.com");
    assert_eq!(config.app.storage_path, "/var/lib/calibre");
    assert_eq!(config.database.url, "sqlite://books.db");
    assert_eq!(
        config.auth.jwt_secret,
        "MDEyMzQ1Njc4OWFiY2RlZjAxMjM0NTY3ODlhYmNkZWY"
    );
}

#[tokio::test]
async fn test_env_vars_override_file() {
    let _guard = env_lock().lock().await;
    let dir = tempfile::tempdir().unwrap();
    let path = dir.path().join("config.toml");
    std::fs::write(
        &path,
        r#"
[app]
base_url = "https://example.com"
storage_path = "/var/lib/calibre"

[database]
url = "sqlite://books.db"
"#,
    )
    .unwrap();

    std::env::set_var("CONFIG_PATH", &path);
    std::env::set_var("APP_BASE_URL", "https://override.example.com");
    std::env::set_var("APP_STORAGE_PATH", "/override/storage");
    std::env::set_var("APP_DATABASE_URL", "sqlite://override.db");
    std::env::set_var("APP_LLM_ENABLED", "true");
    let config = backend::config::load_config().await.unwrap();
    std::env::remove_var("CONFIG_PATH");
    std::env::remove_var("APP_BASE_URL");
    std::env::remove_var("APP_STORAGE_PATH");
    std::env::remove_var("APP_DATABASE_URL");
    std::env::remove_var("APP_LLM_ENABLED");

    assert_eq!(config.app.base_url, "https://override.example.com");
    assert_eq!(config.app.storage_path, "/override/storage");
    assert_eq!(config.database.url, "sqlite://override.db");
    assert!(config.llm.enabled);
}

#[tokio::test]
async fn test_missing_required_fields_error() {
    let _guard = env_lock().lock().await;
    let dir = tempfile::tempdir().unwrap();
    let path = dir.path().join("config.toml");
    std::fs::write(
        &path,
        r#"
[app]
base_url = ""
storage_path = ""

[database]
url = ""
"#,
    )
    .unwrap();

    std::env::set_var("CONFIG_PATH", &path);
    let result = backend::config::load_config().await;
    std::env::remove_var("CONFIG_PATH");

    assert!(result.is_err());
}

#[tokio::test]
async fn test_jwt_secret_autogenerated_when_blank() {
    let _guard = env_lock().lock().await;
    let dir = tempfile::tempdir().unwrap();
    let path = dir.path().join("config.toml");
    std::fs::write(
        &path,
        r#"
[app]
base_url = "https://example.com"
storage_path = "/var/lib/calibre"

[database]
url = "sqlite://books.db"

[auth]
jwt_secret = ""
"#,
    )
    .unwrap();

    std::env::set_var("CONFIG_PATH", &path);
    let config = backend::config::load_config().await.unwrap();
    std::env::remove_var("CONFIG_PATH");

    assert!(!config.auth.jwt_secret.is_empty());
    let rewritten = std::fs::read_to_string(&path).unwrap();
    assert!(rewritten.contains("jwt_secret"));
    assert!(!rewritten.contains("jwt_secret = \"\""));
}

#[tokio::test]
async fn test_jwt_secret_must_be_base64_and_256_bits() {
    let _guard = env_lock().lock().await;
    let dir = tempfile::tempdir().unwrap();
    let path = dir.path().join("config.toml");
    std::fs::write(
        &path,
        r#"
[app]
base_url = "https://example.com"
storage_path = "/var/lib/calibre"

[database]
url = "sqlite://books.db"

[auth]
jwt_secret = "Zm9vYmFy"
"#,
    )
    .unwrap();

    std::env::set_var("CONFIG_PATH", &path);
    let result = backend::config::load_config().await;
    std::env::remove_var("CONFIG_PATH");

    assert!(result.is_err());
}

#[tokio::test]
async fn test_llm_private_endpoint_allowed_with_warning() {
    let _guard = env_lock().lock().await;
    let dir = tempfile::tempdir().unwrap();
    let path = dir.path().join("config.toml");
    std::fs::write(
        &path,
        r#"
[app]
base_url = "https://example.com"
storage_path = "/var/lib/calibre"

[database]
url = "sqlite://books.db"

[auth]
jwt_secret = "MDEyMzQ1Njc4OWFiY2RlZjAxMjM0NTY3ODlhYmNkZWY"

[llm]
enabled = false
allow_private_endpoints = false

[llm.librarian]
endpoint = "http://192.168.1.20:1234/v1"
"#,
    )
    .unwrap();

    std::env::set_var("CONFIG_PATH", &path);
    let result = backend::config::load_config().await;
    std::env::remove_var("CONFIG_PATH");

    assert!(result.is_ok());
}

#[tokio::test]
async fn test_llm_endpoint_rejects_non_http_scheme() {
    let _guard = env_lock().lock().await;
    let dir = tempfile::tempdir().unwrap();
    let path = dir.path().join("config.toml");
    std::fs::write(
        &path,
        r#"
[app]
base_url = "https://example.com"
storage_path = "/var/lib/calibre"

[database]
url = "sqlite://books.db"

[auth]
jwt_secret = "MDEyMzQ1Njc4OWFiY2RlZjAxMjM0NTY3ODlhYmNkZWY"

[llm]
enabled = true

[llm.librarian]
endpoint = "file:///tmp/model.sock"
"#,
    )
    .unwrap();

    std::env::set_var("CONFIG_PATH", &path);
    let result = backend::config::load_config().await;
    std::env::remove_var("CONFIG_PATH");

    assert!(result.is_err());
}

#[tokio::test]
async fn test_world_readable_config_logs_warning() {
    let _guard = env_lock().lock().await;
    let dir = tempfile::tempdir().unwrap();
    let path = dir.path().join("config.toml");
    std::fs::write(
        &path,
        r#"
[app]
base_url = "https://example.com"
storage_path = "/var/lib/calibre"

[database]
url = "sqlite://books.db"
"#,
    )
    .unwrap();

    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt;
        let mut perms = std::fs::metadata(&path).unwrap().permissions();
        perms.set_mode(0o644);
        std::fs::set_permissions(&path, perms).unwrap();
    }

    std::env::set_var("CONFIG_PATH", &path);
    let config = backend::config::load_config().await.unwrap();
    std::env::remove_var("CONFIG_PATH");

    assert_eq!(config.app.base_url, "https://example.com");
}

#[tokio::test]
async fn test_llm_disabled_by_default() {
    let config = backend::config::AppConfig::default();
    assert!(!config.llm.enabled);
}

#[tokio::test]
async fn test_debug_output_redacts_jwt_secret() {
    let mut config = backend::config::AppConfig::default();
    config.auth.jwt_secret = "super-secret".to_string();
    let debug = format!("{:?}", config);
    assert!(!debug.contains("super-secret"));
    assert!(debug.contains("[REDACTED]"));
}
